export const ratings = {
  "Programming Languages": {
    C: 3,
    "C++": 2,
    Golang: 3,
    Groovy: 4,
    Haskell: 3,
    Java: 5,
    JavaScript: 3,
    Python: 5,
    Ruby: 3,
    Scala: 2,
    Shell: 2,
    TypeScript: 4,
  },
  Frameworks: {
    Guice: 3,
    Pytest: 5,
    React: 4,
    Spring: 3,
  },
  Tools: {
    Ansible: 3,
    "Apache Kafka": 4,
    Chef: 5,
    Docker: 5,
    "Docker-Compose": 5,
    Jenkins: 5,
    MySQL: 4,
    PostgreSQL: 3,
    Terraform: 4,
    Tomcat: 2,
  },
  Libraries: {
    Flask: 5,
    Pandas: 4,
    "Scikit-learn": 3,
    XGBoost: 2,
  },
  Concepts: {
    "12 Factor App": 3,
    "Agile Methodologies": 5,
    "Configuration as code": 3,
    Containerization: 4,
    "Infrastructure as code": 3,
    "Microservice Architecture": 4,
    "Serverless Architecture": 4,
  },
};
