export const ratings = {
  "Programming Languages": {
    "C": 3,
    "C++": 3,
    "Golang": 4,
    "Groovy": 4,
    "Haskell": 3,
    "Java": 4,
    "JavaScript": 3,
    "Python": 5,
    "Ruby": 3,
    "Scala": 2,
    "Shell": 3,
    "TypeScript": 3,
  },
  "Frameworks": {
    "Flask": 5,
    "Pytest": 5,
    "React": 4,
    "Spring": 3,
  },
  "Tools": {
    "Ansible": 3,
    "Apache Kafka": 4,
    "Chef": 5,
    "Docker": 5,
    "Docker-Compose": 5,
    "Jenkins": 5,
    "MySQL": 4,
    "PostgreSQL": 3,
    "Terraform": 4,
  },
  "Libraries": {
    "Pandas": 4,
    "Scikit-learn": 3,
  },
  "Concepts": {
    "12 Factor App": 3,
    "Agile Methodologies": 5,
    "Configuration as code": 3,
    "Containerization": 4,
    "Microservice Architecture": 4,
    "Serverless Architecture": 4,
  },
};